services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PropertyManagementApp
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - pm
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pm
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pm
      MYSQL_USER: pm
      MYSQL_PASSWORD: pm
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pm

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: pm
      PMA_PASSWORD: pm
    ports:
      - "8010:80"
    networks:
      - pm
    depends_on:
      - db

networks:
  pm:

volumes:
  dbdata:
